sudo: required
language: generic
services: 
  - docker

  before_install:
  - docker build -t pravallikavasi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pravallikavasi/docker-react npm run test -- --coverage
